# Generated by Django 3.2.5 on 2021-07-20 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enroll', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone_no',
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
    ]
